name: check-version

on:
  schedule:
  - cron: "23 1 * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/datalad/datalad/releases/latest | \
          jq -r ".tag_name"
          xargs printf 'version=%s\n' >> $GITHUB_STATE
      - name: Validate version
        run: |
          if [[ {{ env.version }} =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
            tee {{ env.version }} version.txt
          else
            echo "Unrecognized version {{ env.version }}"
            exit 1
          fi
      - name: Check for modified files
        id: git-check
        run: |
          echo "modified=$(\
            [ -z "$(git status --porcelain)" ] && echo "false" || echo "true"\
          )" >> $GITHUB_STATE
      - name: Commit latest release version
        if: env.modified == 'true'
        run: |
          git commit -am "New release version"
          git push